name: lottery_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  avatar_glow: ^2.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_shimmer: ^2.1.1
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  get: 4.3.8
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  http: ^0.13.3
  multiavatar: ^0.1.5
  url_launcher: ^6.0.9
  web3dart: ^2.2.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
